---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(laGP)
eps <- sqrt(.Machine$double.eps)
eps
```


```{r}
set.seed(1)
n <- 10
b0 <- 1
b1 <- 0.5
df <- data.frame(nx = seq(1, 10, length.out = n)) %>% 
  mutate(ny = b0 + b1 * nx + rnorm(n, sd = b1))
df
```

```{r}
df %>% 
  ggplot(aes(nx, ny)) +
  geom_point() +
  geom_smooth(method = "lm") +
  coord_equal()
```

```{r}
df1 <-
  df %>% 
  mutate(
    x = (nx - min(nx)) / (max(nx) - min(nx)),
    y = (ny - min(ny)) / (max(ny) - min(ny)),
  )

df1 %>% 
  ggplot(aes(x, y)) +
  geom_point() +
  geom_line() +
  coord_equal()
```


```{r}
gpi <- newGP(matrix(df1$x, ncol=1), df1$y, 
             d = 0.1, g = eps, dK = TRUE)
m <- mleGP(gpi, tmax = 1000000000)
m
p <- predGP(gpi, matrix(df1$x, ncol=1), lite=TRUE)
p
```


```{r}
df1$mean = p$mean
df1$s2 = p$s2
df1
```

```{r}
df1 %>% 
  mutate(np = (max(ny) - min(ny)) * mean + min(ny)) %>% 
  ggplot(aes(nx, ny)) + 
  geom_point() +
  geom_line(aes(y = np)) +
  geom_smooth(method = "lm")
  #coord_equal()
```

```{r}
lm_fit <- lm(y ~ x, data = select(df1, x, y))
summary(lm_fit)
```

```{r}
df1 %>% 
  mutate(p_lm = predict(lm_fit)) %>% 
  ggplot(aes(y, p_lm - mean)) +
  geom_point()
```



```{r}
test <- tibble(x = seq(0, 2, length.out = 100))
test$lm = predict(lm_fit, newdata = test)
test
```


```{r}
p <- predGP(gpi, matrix(test$x, ncol=1), lite=TRUE)
test$gpm <- p$mean
test$gps2 <- p$s2
test
```

```{r}
test %>% 
  mutate(
    ql = qnorm(0.05, sd = sqrt(gps2)),
    qu = qnorm(0.95, sd = sqrt(gps2)),
  ) %>% 
  ggplot(aes(x = x)) +
  geom_line(aes(y = lm)) +
  geom_line(aes(y = gpm), color = "red") +
  geom_linerange(aes(x = x, ymin = gpm + ql, ymax = gpm + qu))
  
```

```{r}
predict(lm_fit, newdata = data.frame(x = 1:20))
```


```{r}
df1
```



```{r}
ball <- read.csv("dataset/ball.csv")
ball
```


```{r}
dfb <- tibble(ball)
dfb %>% 
  ggplot(aes(height, time)) +
  geom_point() +
  #geom_smooth(method = "lm", formula = "y ~ poly(x, 2)") +
  geom_smooth(method = "lm", formula = "y ~ sqrt(x)")
```


```{r}
field.fit <- newGP(as.matrix(ball$height), ball$time, d=0.1,
                  g=var(ball$time)/10, dK=TRUE)
                  #g=1e-6, dK=TRUE)
eps <- sqrt(.Machine$double.eps)
mle <- jmleGP(field.fit, drange=c(eps, 10), grange=c(eps, var(ball$time)),
              dab=c(3/2, 8))
              #gab=c(3/2, 6))
mle
hr <- range(ball$height)
hs <- seq(0, 1, length=100)
heights <- hs*diff(hr) + hr[1]
p <- predGP(field.fit, as.matrix(heights), lite=TRUE)
deleteGP(field.fit)

plot(ball, xlab="height", ylab="time")
lines(heights, p$mean, col=4)
lines(heights, qnorm(0.05, p$mean, sqrt(p$s2)), lty=2, col=4)
lines(heights, qnorm(0.95, p$mean, sqrt(p$s2)), lty=2, col=4)
lines(heights, 10*sqrt(p$s2)-0.6, col=2, lty=3, lwd=2)
legend("topleft", c("Fhat summary", "Fhat sd"), lty=c(1,3),
  col=c(4,2), lwd=1:2)
```


```{r}
mle
```

















